import Chat from '@/components/Chat';
import Login from '@/components/Login';
import Sidebar from '@/components/Sidebar';
import { Bars3Icon } from '@heroicons/react/24/solid';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const { data: session } = useSession();
  const [showSidebar, setShowSidebar] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!session ? (
        <Login />
      ) : (
        <main className="flex">
          <div
            className={`bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem] `}
          >
            <Sidebar />
          </div>

          {/* Client side notification */}

          <div className="bg-[#343541] flex-1">
            <Chat />
          </div>
        </main>
      )}
    </>
  );
}
